steps:

# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/$_CUSTOM_IMAGE_NAME:$BUILD_ID'
    - '-t'
    - 'gcr.io/$PROJECT_ID/$_CUSTOM_IMAGE_NAME:latest'
    - '.'

# Push Docker tags
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_CUSTOM_IMAGE_NAME']

# deploy helm chart
- name: 'gcr.io/$PROJECT_ID/helm'
  args:
    - 'upgrade'
    - '-i'
    - $_HELM_RELEASE_NAME
    - $_HELM_CHART_NAME
    - '--set'
    - 'image.repository=gcr.io/$PROJECT_ID/$_CUSTOM_IMAGE_NAME,image.tag=$BUILD_ID'
    - '--set'
    - 'cloud_sql_proxy.instanceConnectionName=$PROJECT_ID:$_CUSTOM_REGION:$_CLOUD_SQL_DBNAME'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_CUSTOM_ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER'

substitutions:
  _CUSTOM_IMAGE_NAME: sample-python-app
  _HELM_RELEASE_NAME: sample-python-app
  _HELM_CHART_NAME: ./helm/sample-python-app/
  _CUSTOM_REGION:
  _CUSTOM_ZONE:
  _CUSTOM_CLUSTER:
  _CLOUD_SQL_DBNAME:
